# Generated by Django 4.1.3 on 2023-03-20 15:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_workout_workout_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='workout_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_list', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, default=list, size=None), blank=True, default=list, size=None)),
                ('workout_names', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5000), blank=True, default=list, size=None)),
                ('numberOfWorkout', models.IntegerField()),
                ('goal', models.CharField(max_length=1000)),
            ],
        ),
    ]
